module.exports = {
  testEnvironment: 'node',
  preset: 'ts-jest',
  rootDir: './',
  modulePaths: ['<rootDir>'],
  moduleNameMapper: {
    '^src$': '<rootDir>/src',
    '^src/(.+)$': '<rootDir>/src/$1',
    '^@common$': '<rootDir>/src/common',
    '^@common/(.+)$': '<rootDir>/src/common/$1',
    '^@config$': '<rootDir>/src/config',
    '^@config/(.+)$': '<rootDir>/src/config/$1',
    '^@modules$': '<rootDir>/src/modules',
    '^@modules/(.+)$': '<rootDir>/src/modules/$1',
    '^@database$': '<rootDir>/src/database',
    '^@database/(.+)$': '<rootDir>/src/database/$1',
    '^@queues$': '<rootDir>/src/queues',
    '^@queues/(.+)$': '<rootDir>/src/queues/$1',
    '^@types$': '<rootDir>/src/types',
    '^@types/(.+)$': '<rootDir>/src/types/$1',
  },
  modulePathIgnorePatterns: ['src/typings'],
  testPathIgnorePatterns: ['/node_modules/', '<rootDir>/(coverage|dist|lib|tmp)/'],
};
